/** @deprecated Use @/lib/football-api — kept for backward compatibility */
export {
  fetchApiStatus,
  fetchPlayers,
  fetchFixtures,
  fetchPlayerStats,
  fetchLiveScores,
  fetchFixturesByDate,
  fetchLeagueMatches,
  fetchStandings,
  fetchAllLeagues,
  findWorldCupLeagueId,
  fetchWorldCupPlayers,
  fetchWorldCupMatchesForFantasy,
  isFootballApiConfigured,
  WORLD_CUP_LEAGUE_ID,
  DEFAULT_SEASON,
  type ApiMatch,
  type ApiStatusResponse,
  type LiveMatch,
  type FootballPlayer,
  type FootballLeague,
} from "./football-api";
