// Multi-country regions for raffles, business profiles, and user profiles.
// Backwards compatible: PROVINCES/CITIES_BY_PROVINCE re-exported from provinces.ts

export const COUNTRIES = [
  { code: "MZ", label: "Moçambique", flag: "🇲🇿", currency: "MZN" },
  { code: "AO", label: "Angola", flag: "🇦🇴", currency: "AOA" },
  { code: "PT", label: "Portugal", flag: "🇵🇹", currency: "EUR" },
  { code: "BR", label: "Brasil", flag: "🇧🇷", currency: "BRL" },
  { code: "ZA", label: "África do Sul", flag: "🇿🇦", currency: "ZAR" },
  { code: "US", label: "Estados Unidos", flag: "🇺🇸", currency: "USD" },
  { code: "CV", label: "Cabo Verde", flag: "🇨🇻", currency: "CVE" },
  { code: "GW", label: "Guiné-Bissau", flag: "🇬🇼", currency: "XOF" },
  { code: "ST", label: "São Tomé e Príncipe", flag: "🇸🇹", currency: "STN" },
  { code: "GB", label: "Reino Unido", flag: "🇬🇧", currency: "GBP" },
  { code: "FR", label: "França", flag: "🇫🇷", currency: "EUR" },
  { code: "ES", label: "Espanha", flag: "🇪🇸", currency: "EUR" },
] as const;

export type CountryCode = typeof COUNTRIES[number]["code"];

// Regions / states / provinces per country (top-level admin divisions).
export const REGIONS_BY_COUNTRY: Record<string, { value: string; label: string }[]> = {
  MZ: [
    { value: "maputo-cidade", label: "Maputo Cidade" },
    { value: "maputo", label: "Maputo Província" },
    { value: "gaza", label: "Gaza" },
    { value: "inhambane", label: "Inhambane" },
    { value: "sofala", label: "Sofala" },
    { value: "manica", label: "Manica" },
    { value: "tete", label: "Tete" },
    { value: "zambezia", label: "Zambézia" },
    { value: "nampula", label: "Nampula" },
    { value: "niassa", label: "Niassa" },
    { value: "cabo-delgado", label: "Cabo Delgado" },
  ],
  AO: [
    { value: "luanda", label: "Luanda" },
    { value: "benguela", label: "Benguela" },
    { value: "huambo", label: "Huambo" },
    { value: "huila", label: "Huíla" },
    { value: "namibe", label: "Namibe" },
    { value: "cabinda", label: "Cabinda" },
    { value: "bie", label: "Bié" },
    { value: "uige", label: "Uíge" },
    { value: "malanje", label: "Malanje" },
    { value: "cuanza-sul", label: "Cuanza Sul" },
    { value: "cuanza-norte", label: "Cuanza Norte" },
    { value: "zaire", label: "Zaire" },
    { value: "lunda-norte", label: "Lunda Norte" },
    { value: "lunda-sul", label: "Lunda Sul" },
    { value: "moxico", label: "Moxico" },
    { value: "bengo", label: "Bengo" },
    { value: "cunene", label: "Cunene" },
    { value: "cuando-cubango", label: "Cuando Cubango" },
  ],
  PT: [
    { value: "lisboa", label: "Lisboa" },
    { value: "porto", label: "Porto" },
    { value: "braga", label: "Braga" },
    { value: "coimbra", label: "Coimbra" },
    { value: "aveiro", label: "Aveiro" },
    { value: "faro", label: "Faro (Algarve)" },
    { value: "setubal", label: "Setúbal" },
    { value: "leiria", label: "Leiria" },
    { value: "viseu", label: "Viseu" },
    { value: "santarem", label: "Santarém" },
    { value: "evora", label: "Évora" },
    { value: "madeira", label: "Madeira" },
    { value: "acores", label: "Açores" },
  ],
  BR: [
    { value: "sp", label: "São Paulo" },
    { value: "rj", label: "Rio de Janeiro" },
    { value: "mg", label: "Minas Gerais" },
    { value: "rs", label: "Rio Grande do Sul" },
    { value: "pr", label: "Paraná" },
    { value: "ba", label: "Bahia" },
    { value: "sc", label: "Santa Catarina" },
    { value: "pe", label: "Pernambuco" },
    { value: "ce", label: "Ceará" },
    { value: "go", label: "Goiás" },
    { value: "df", label: "Distrito Federal" },
    { value: "es", label: "Espírito Santo" },
    { value: "pa", label: "Pará" },
    { value: "am", label: "Amazonas" },
    { value: "ma", label: "Maranhão" },
    { value: "mt", label: "Mato Grosso" },
    { value: "ms", label: "Mato Grosso do Sul" },
    { value: "rn", label: "Rio Grande do Norte" },
    { value: "pb", label: "Paraíba" },
    { value: "al", label: "Alagoas" },
  ],
  ZA: [
    { value: "gauteng", label: "Gauteng" },
    { value: "western-cape", label: "Western Cape" },
    { value: "kwazulu-natal", label: "KwaZulu-Natal" },
    { value: "eastern-cape", label: "Eastern Cape" },
    { value: "limpopo", label: "Limpopo" },
    { value: "mpumalanga", label: "Mpumalanga" },
    { value: "north-west", label: "North West" },
    { value: "free-state", label: "Free State" },
    { value: "northern-cape", label: "Northern Cape" },
  ],
  US: [
    { value: "ca", label: "California" },
    { value: "tx", label: "Texas" },
    { value: "fl", label: "Florida" },
    { value: "ny", label: "New York" },
    { value: "il", label: "Illinois" },
    { value: "pa", label: "Pennsylvania" },
    { value: "oh", label: "Ohio" },
    { value: "ga", label: "Georgia" },
    { value: "nc", label: "North Carolina" },
    { value: "mi", label: "Michigan" },
    { value: "nj", label: "New Jersey" },
    { value: "va", label: "Virginia" },
    { value: "wa", label: "Washington" },
    { value: "ma", label: "Massachusetts" },
    { value: "az", label: "Arizona" },
  ],
  CV: [
    { value: "praia", label: "Praia" },
    { value: "mindelo", label: "Mindelo" },
    { value: "sal", label: "Sal" },
    { value: "boa-vista", label: "Boa Vista" },
    { value: "santo-antao", label: "Santo Antão" },
    { value: "fogo", label: "Fogo" },
  ],
  GW: [
    { value: "bissau", label: "Bissau" },
    { value: "bafata", label: "Bafatá" },
    { value: "gabu", label: "Gabú" },
  ],
  ST: [
    { value: "sao-tome", label: "São Tomé" },
    { value: "principe", label: "Príncipe" },
  ],
  GB: [
    { value: "england", label: "England" },
    { value: "scotland", label: "Scotland" },
    { value: "wales", label: "Wales" },
    { value: "northern-ireland", label: "Northern Ireland" },
  ],
  FR: [
    { value: "ile-de-france", label: "Île-de-France" },
    { value: "paca", label: "Provence-Alpes-Côte d'Azur" },
    { value: "auvergne-rhone-alpes", label: "Auvergne-Rhône-Alpes" },
    { value: "occitanie", label: "Occitanie" },
    { value: "nouvelle-aquitaine", label: "Nouvelle-Aquitaine" },
    { value: "hauts-de-france", label: "Hauts-de-France" },
  ],
  ES: [
    { value: "madrid", label: "Madrid" },
    { value: "cataluna", label: "Cataluña" },
    { value: "andalucia", label: "Andalucía" },
    { value: "valencia", label: "Comunidad Valenciana" },
    { value: "galicia", label: "Galicia" },
    { value: "pais-vasco", label: "País Vasco" },
  ],
};

export function getRegions(country: string) {
  return REGIONS_BY_COUNTRY[country] ?? [];
}

export function getCountryLabel(code: string) {
  return COUNTRIES.find((c) => c.code === code)?.label ?? code;
}
