project_id = "ngxrdpplyghlugoowjqj"

[functions]
  [functions.admin-cron-jobs]
    verify_jwt = true
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.auto-draw]
    verify_jwt = true
  [functions.award-engagement-points]
    verify_jwt = true
  [functions.check-ticket-threshold]
    verify_jwt = false
  [functions.create-admin]
    verify_jwt = true
  [functions.draw-social-winner]
    verify_jwt = true
  [functions.fetch-football-data]
    verify_jwt = false
  [functions.mascot-chat]
    verify_jwt = false
  [functions.mascot-message]
    verify_jwt = false
  [functions.notify-payment-receipt]
    verify_jwt = false
  [functions.notify-raffle-ending]
    verify_jwt = true
  [functions.paypal-capture-order]
    verify_jwt = true
  [functions.paypal-config]
    verify_jwt = false
  [functions.paypal-create-order]
    verify_jwt = true
  [functions.process-email-queue]
    verify_jwt = true
  [functions.spin-wheel-spin]
    verify_jwt = true
  [functions.track-ambassador-visit]
    verify_jwt = false
