// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-raffles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-raffles.ts
var search_raffles_default = defineTool({
  name: "search_raffles",
  title: "Search raffles",
  description: "Search active raffles on Bateu by title, category or country.",
  inputSchema: {
    query: z.string().trim().optional().describe("Text to match against the raffle title."),
    country: z.string().trim().optional().describe("Two-letter country code, e.g. US, CA, PT, BR, MZ, AO."),
    category: z.string().trim().optional().describe("Raffle category filter."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, country, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("raffles").select("id, slug, title, prize_title, prize_value, ticket_price, currency, sold_tickets, total_tickets, end_date, status, country, category").eq("status", "active").order("end_date", { ascending: true }).limit(limit ?? 10);
    if (query) q = q.ilike("title", `%${query}%`);
    if (country) q = q.eq("country", country.toUpperCase());
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { raffles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-raffle.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_raffle_default = defineTool2({
  name: "get_raffle",
  title: "Get raffle details",
  description: "Get the full public details of one Bateu raffle by its slug or id.",
  inputSchema: {
    slug: z2.string().trim().optional().describe("Raffle slug from the public URL."),
    id: z2.string().uuid().optional().describe("Raffle UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!slug && !id) {
      return { content: [{ type: "text", text: "Provide either slug or id." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("raffles").select("id, slug, title, description, prize_title, prize_value, hide_prize_value, ticket_price, currency, sold_tickets, total_tickets, max_tickets_per_user, status, start_date, end_date, category, country, province, city, image_url").limit(1);
    q = slug ? q.eq("slug", slug) : q.eq("id", id);
    const { data, error } = await q.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Raffle not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { raffle: data }
    };
  }
});

// src/lib/mcp/tools/list-my-tickets.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_tickets_default = defineTool3({
  name: "list_my_tickets",
  title: "List my tickets",
  description: "List the signed-in user's Bateu raffle tickets and their payment status.",
  inputSchema: {
    payment_status: z3.enum(["pending", "approved", "rejected"]).optional().describe("Filter by payment status."),
    limit: z3.number().int().min(1).max(100).optional().describe("Maximum results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ payment_status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("participants").select("id, ticket_number, status, payment_status, payment_method, currency, created_at, raffle_id, raffles(title, slug, status, end_date)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (payment_status) q = q.eq("payment_status", payment_status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tickets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-luck-points.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_my_luck_points_default = defineTool4({
  name: "get_my_luck_points",
  title: "Get my Luck Points",
  description: "Get the signed-in user's Luck Points balance and recent point activity on Bateu.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("How many recent entries to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("luck_points").select("id, points, action, description, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const entries = data ?? [];
    const total = entries.reduce((sum, row) => sum + (row.points ?? 0), 0);
    return {
      content: [{ type: "text", text: JSON.stringify({ recent_total: total, entries }) }],
      structuredContent: { recent_total: total, entries }
    };
  }
});

// src/lib/mcp/tools/list-my-notifications.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_my_notifications_default = defineTool5({
  name: "list_my_notifications",
  title: "List my notifications",
  description: "List the signed-in user's Bateu notifications, newest first.",
  inputSchema: {
    unread_only: z5.boolean().optional().describe("Return only unread notifications."),
    limit: z5.number().int().min(1).max(100).optional().describe("Maximum results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("notifications").select("id, title, message, type, read, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (unread_only) q = q.eq("read", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/mark-notification-read.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var mark_notification_read_default = defineTool6({
  name: "mark_notification_read",
  title: "Mark notification as read",
  description: "Mark one of the signed-in user's Bateu notifications as read.",
  inputSchema: {
    notification_id: z6.string().uuid().describe("The notification UUID to mark as read.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ notification_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("notifications").update({ read: true }).eq("id", notification_id).eq("user_id", ctx.getUserId()).select("id, read");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: "Notification not found." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data[0]) }],
      structuredContent: { notification: data[0] }
    };
  }
});

// src/lib/mcp/tools/list-businesses.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var list_businesses_default = defineTool7({
  name: "list_businesses",
  title: "List businesses",
  description: "Browse the public Bateu business directory of verified organizers.",
  inputSchema: {
    query: z7.string().trim().optional().describe("Filter businesses whose name contains this text."),
    limit: z7.number().int().min(1).max(50).optional().describe("Maximum results (default 12).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_business_directory");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const needle = query?.toLowerCase();
    const filtered = needle ? rows.filter((r) => String(r.company_name ?? r.display_name ?? "").toLowerCase().includes(needle)) : rows;
    const limited = filtered.slice(0, limit ?? 12);
    return {
      content: [{ type: "text", text: JSON.stringify(limited) }],
      structuredContent: { businesses: limited }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ngxrdpplyghlugoowjqj";
var mcp_default = defineMcp({
  name: "bateu",
  title: "Bateu",
  version: "0.1.0",
  instructions: "Tools for Bateu, a raffle and live-prize platform. Browse active raffles and verified business organizers, and read the signed-in user's tickets, Luck Points and notifications. All data is scoped to the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_raffles_default,
    get_raffle_default,
    list_my_tickets_default,
    get_my_luck_points_default,
    list_my_notifications_default,
    mark_notification_read_default,
    list_businesses_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
