ALTER TABLE public.raffles ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'USD';
ALTER TABLE public.raffles ADD COLUMN IF NOT EXISTS country text NOT NULL DEFAULT 'US';
ALTER TABLE public.participants ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'USD';
ALTER TABLE public.participants ADD COLUMN IF NOT EXISTS paypal_order_id text;
ALTER TABLE public.participants ADD COLUMN IF NOT EXISTS paypal_capture_id text;
ALTER TABLE public.participants ALTER COLUMN payment_method SET DEFAULT 'paypal';
ALTER TABLE public.prestacao_products ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'USD';

DELETE FROM public.participants;
DELETE FROM public.bolao_members;
DELETE FROM public.boloes;
DELETE FROM public.blockchain_verifications;
DELETE FROM public.social_participations;
DELETE FROM public.social_raffle_entries;
DELETE FROM public.raffles;
DELETE FROM public.contest_votes;
DELETE FROM public.contest_submissions;
DELETE FROM public.contests;
DELETE FROM public.live_ambassador_visits;
DELETE FROM public.live_ambassador_prizes;
DELETE FROM public.live_ambassadors;
DELETE FROM public.scheduled_live_attendance;
DELETE FROM public.scheduled_live_links;
DELETE FROM public.live_studio_checklist;
DELETE FROM public.scheduled_lives;
DELETE FROM public.live_poll_votes;
DELETE FROM public.live_polls;
DELETE FROM public.live_announcements;
DELETE FROM public.user_stories;
DELETE FROM public.message_likes;
DELETE FROM public.community_messages;
DELETE FROM public.notifications;
DELETE FROM public.prestacao_product_leads;
DELETE FROM public.prestacao_products;
DELETE FROM public.redeemed_rewards;
DELETE FROM public.luck_points;
DELETE FROM public.referrals;